In [1]:
import pandas as pd

import csv
import math

In [2]:
!ls '../Complete'
!ls '../'

country_vaccinations.csv       population_by_country_2020.csv
owid-covid-data.csv
Complete        Data_Management Modified

# Modify the Vaccinations Data

In [3]:
filepath = '../Complete/country_vaccinations.csv'

df = pd.read_csv(filepath) 
df

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7612,Zimbabwe,ZWE,2021-03-17,39607.0,39607.0,NaN,57.0,529.0,0.27,0.27,NaN,36.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...
7613,Zimbabwe,ZWE,2021-03-18,40002.0,40002.0,NaN,395.0,569.0,0.27,0.27,NaN,38.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...
7614,Zimbabwe,ZWE,2021-03-19,41687.0,41687.0,NaN,1685.0,772.0,0.28,0.28,NaN,52.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...
7615,Zimbabwe,ZWE,2021-03-20,42210.0,42210.0,NaN,523.0,836.0,0.28,0.28,NaN,56.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...
7616,Zimbabwe,ZWE,2021-03-21,42729.0,42729.0,NaN,519.0,910.0,0.29,0.29,NaN,61.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...

In [4]:
dictionary = {}
for index, row in df.iterrows():
    if(dictionary.__contains__(row.country)):
        if(math.isnan(dictionary[row.country])):
            dictionary[row.country] = row.total_vaccinations
        dictionary[row.country] += row.total_vaccinations
    else:
        dictionary[row.country] = row.total_vaccinations
        
iso_code = df['iso_code'].unique()
print(len(iso_code) == len(dictionary))

data = []
for i, key in enumerate(dictionary.keys()):
    data.append((key, iso_code[i], dictionary[key]))
    
df2 = pd.DataFrame(data, columns=["Name", "ISO_Code", "Total_Vaccinations"])
df2

True

            Name  ISO_Code  Total_Vaccinations
0    Afghanistan       AFG            108000.0
1        Albania       ALB             66738.0
2        Algeria       DZA            150000.0
3        Andorra       AND              9828.0
4         Angola       AGO             98000.0
..           ...       ...                 ...
145      Uruguay       URY           3375734.0
146    Venezuela       VEN             24388.0
147      Vietnam       VNM            149464.0
148        Wales  OWID_WLS          51820593.0
149     Zimbabwe       ZWE            809060.0

[150 rows x 3 columns]

In [5]:
df2.to_csv('../Modified/Total_Vaccinations.csv', index=False)

# Modify the Covid Cases Data

In [22]:
filepath = '../Complete/owid-covid-data.csv'

df = pd.read_csv(filepath) 
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76617,ZWE,Africa,Zimbabwe,2021-03-18,36611.0,59.0,33.429,1509.0,1.0,2.429,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
76618,ZWE,Africa,Zimbabwe,2021-03-19,36652.0,41.0,32.714,1510.0,1.0,2.000,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
76619,ZWE,Africa,Zimbabwe,2021-03-20,36662.0,10.0,27.286,1510.0,0.0,1.286,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
76620,ZWE,Africa,Zimbabwe,2021-03-21,36665.0,3.0,25.857,1512.0,2.0,1.286,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
76621,ZWE,Africa,Zimbabwe,2021-03-22,36684.0,19.0,25.714,1514.0,2.0,1.429,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571

In [23]:
dictionary = {}
for index, row in df.iterrows():
    if(dictionary.__contains__(row.location)):
        if(math.isnan(dictionary[row.location])):
            dictionary[row.location] = row.total_cases
        dictionary[row.location] += row.total_cases
    else:
        dictionary[row.location] = row.total_cases
        
iso_code = df['iso_code'].unique()
print(len(iso_code) == len(dictionary))

data = []
for i, key in enumerate(dictionary.keys()):
    data.append((key, iso_code[i], dictionary[key]))
    
df2 = pd.DataFrame(data, columns=["Name", "ISO_Code", "Total_Cases"])
df2

True

            Name  ISO_Code   Total_Cases
0    Afghanistan       AFG  1.293724e+07
1         Africa  OWID_AFR  5.860571e+08
2        Albania       ALB  1.096648e+07
3        Algeria       DZA  1.941948e+07
4        Andorra       AND  1.501686e+06
..           ...       ...           ...
210      Vietnam       VNM  3.849210e+05
211        World  OWID_WRL  1.622353e+10
212        Yemen       YEM  5.692420e+05
213       Zambia       ZMB  7.308239e+06
214     Zimbabwe       ZWE  3.908763e+06

[215 rows x 3 columns]

In [24]:
df2.to_csv('../Modified/Total_Cases.csv', index=False)

# Do calculations with population by country

In [67]:
filepath = '../Complete/population_by_country_2020.csv'

df_pop = pd.read_csv(filepath) 
df_pop

,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,China,1440297825,0.39%,5540090.0,153.0,9388211.0,-348399.0,1.7,38,61%,18.47%
1,India,1382345085,0.99%,13586631.0,464.0,2973190.0,-532687.0,2.2,28,35%,17.70%
2,United States,331341050,0.59%,1937734.0,36.0,9147420.0,954806.0,1.8,38,83%,4.25%
3,Indonesia,274021604,1.07%,2898047.0,151.0,1811570.0,-98955.0,2.3,30,56%,3.51%
4,Pakistan,221612785,2.00%,4327022.0,287.0,770880.0,-233379.0,3.6,23,35%,2.83%
...,...,...,...,...,...,...,...,...,...,...,...
245,Kosovo,1860000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,Micronesia (country),548914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,North America,368869647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,Northern Cyprus,326000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,Palestine,5186734,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
data = []

dictionary2 = {}
for index, row in df_pop.iterrows():
    if(dictionary2.__contains__(row["Country (or dependency)"])):
        if(math.isnan(dictionary2[row["Country (or dependency)"]])):
            dictionary2[row["Country (or dependency)"]] = row["Population (2020)"]
        dictionary2[row["Country (or dependency)"]] += row["Population (2020)"]
    else:
        dictionary2[row["Country (or dependency)"]] = row["Population (2020)"]

data = []
print(dictionary["International"])
print(dictionary2["Czechia"])
for i, key in enumerate(dictionary.keys()):
    if(key == "International" or key == "Oceania"  or key == "Saint Kitts and Nevis"):
        continue
    data.append((key, iso_code[i], dictionary[key], dictionary2[key], (dictionary[key]/dictionary2[key] * 100)))
    
df2 = pd.DataFrame(data, columns=["Name", "ISO_Code", "Total_Cases", "Total_Population", "Cases_per_100"])
df2

288728.0
10730000

KeyError: 'Saint Kitts and Nevis'